import Foundation

/// Global catalog of coral-reef sample sites. Each entry is a representative
/// lat/lon used to query the NOAA Coral Reef Watch 5 km gridded product via
/// ERDDAP — they are not required to match NOAA's published Virtual Station
/// names exactly. Coordinates target the center of recognizable reef habitat.
///
/// To swap in NOAA's exact Regional Virtual Station list, replace this array
/// with a JSON manifest loaded at launch (e.g. from
/// https://coralreefwatch.noaa.gov/product/vs/gauges.php).
enum VirtualStationCatalog {
    static let stations: [VirtualStation] = [

        // ─── Australia & Coral Sea ────────────────────────────────────────────
        .init(id: "gbr_far_north",    name: "Great Barrier Reef – Far North", region: "Australia",    latitude: -11.5, longitude: 143.5),
        .init(id: "gbr_north",        name: "Great Barrier Reef – North",     region: "Australia",    latitude: -14.5, longitude: 145.5),
        .init(id: "gbr_central",      name: "Great Barrier Reef – Central",   region: "Australia",    latitude: -19.0, longitude: 148.5),
        .init(id: "gbr_south",        name: "Great Barrier Reef – South",     region: "Australia",    latitude: -22.5, longitude: 152.0),
        .init(id: "coral_sea_osprey", name: "Osprey Reef (Coral Sea)",        region: "Australia",    latitude: -13.9, longitude: 146.6),
        .init(id: "coral_sea_marion", name: "Marion Reef (Coral Sea)",        region: "Australia",    latitude: -19.1, longitude: 152.4),
        .init(id: "torres_strait",    name: "Torres Strait",                  region: "Australia",    latitude: -10.0, longitude: 143.0),
        .init(id: "lord_howe",        name: "Lord Howe Island",               region: "Australia",    latitude: -31.5, longitude: 159.1),
        .init(id: "norfolk_island",   name: "Norfolk Island",                 region: "Australia",    latitude: -29.0, longitude: 167.9),
        .init(id: "ningaloo",         name: "Ningaloo Reef",                  region: "Australia",    latitude: -22.7, longitude: 113.7),
        .init(id: "rowley_shoals",    name: "Rowley Shoals",                  region: "Australia",    latitude: -17.4, longitude: 119.4),
        .init(id: "scott_reef",       name: "Scott Reef",                     region: "Australia",    latitude: -14.0, longitude: 121.8),
        .init(id: "ashmore_reef",     name: "Ashmore Reef",                   region: "Australia",    latitude: -12.2, longitude: 123.0),
        .init(id: "christmas_island", name: "Christmas Island",               region: "Australia",    latitude: -10.5, longitude: 105.6),
        .init(id: "cocos_keeling",    name: "Cocos (Keeling) Islands",        region: "Australia",    latitude: -12.2, longitude: 96.8),

        // ─── Pacific Islands ──────────────────────────────────────────────────
        .init(id: "hawaii_main",      name: "Main Hawaiian Islands",          region: "USA – Pacific",latitude:  20.5, longitude: -157.0),
        .init(id: "hawaii_oahu",      name: "Oʻahu",                          region: "USA – Pacific",latitude:  21.4, longitude: -157.9),
        .init(id: "hawaii_maui",      name: "Maui",                           region: "USA – Pacific",latitude:  20.8, longitude: -156.3),
        .init(id: "hawaii_kona",      name: "Hawaiʻi (Kona)",                 region: "USA – Pacific",latitude:  19.6, longitude: -156.0),
        .init(id: "papahanaumokuakea",name: "Papahānaumokuākea",              region: "USA – Pacific",latitude:  25.5, longitude: -170.0),
        .init(id: "midway",           name: "Midway Atoll",                   region: "USA – Pacific",latitude:  28.2, longitude: -177.4),
        .init(id: "samoa",            name: "American Samoa",                 region: "S. Pacific",   latitude: -14.3, longitude: -170.7),
        .init(id: "samoa_indep",      name: "Samoa (Upolu)",                  region: "S. Pacific",   latitude: -13.9, longitude: -171.7),
        .init(id: "guam",             name: "Guam",                           region: "Micronesia",   latitude:  13.4, longitude: 144.7),
        .init(id: "cnmi_saipan",      name: "Saipan (CNMI)",                  region: "Micronesia",   latitude:  15.2, longitude: 145.7),
        .init(id: "palau",            name: "Palau",                          region: "Micronesia",   latitude:   7.5, longitude: 134.5),
        .init(id: "yap",              name: "Yap",                            region: "Micronesia",   latitude:   9.5, longitude: 138.1),
        .init(id: "chuuk",            name: "Chuuk",                          region: "Micronesia",   latitude:   7.4, longitude: 151.8),
        .init(id: "pohnpei",          name: "Pohnpei",                        region: "Micronesia",   latitude:   6.9, longitude: 158.2),
        .init(id: "kosrae",           name: "Kosrae",                         region: "Micronesia",   latitude:   5.3, longitude: 162.9),
        .init(id: "majuro",           name: "Majuro (RMI)",                   region: "Micronesia",   latitude:   7.1, longitude: 171.2),
        .init(id: "kwajalein",        name: "Kwajalein Atoll",                region: "Micronesia",   latitude:   8.7, longitude: 167.7),
        .init(id: "bikini",           name: "Bikini Atoll",                   region: "Micronesia",   latitude:  11.6, longitude: 165.4),
        .init(id: "phoenix_islands",  name: "Phoenix Islands (Kiribati)",     region: "Pacific",      latitude:  -3.8, longitude: -171.7),
        .init(id: "line_islands",     name: "Line Islands (Kiribati)",        region: "Pacific",      latitude:   1.9, longitude: -157.4),
        .init(id: "gilbert_islands",  name: "Gilbert Islands (Kiribati)",     region: "Pacific",      latitude:   1.5, longitude: 173.0),
        .init(id: "tuvalu",           name: "Tuvalu",                         region: "Pacific",      latitude:  -8.5, longitude: 179.2),
        .init(id: "tokelau",          name: "Tokelau",                        region: "Pacific",      latitude:  -9.2, longitude: -171.8),
        .init(id: "wallis_futuna",    name: "Wallis & Futuna",                region: "Pacific",      latitude: -13.3, longitude: -176.2),
        .init(id: "tonga_tongatapu",  name: "Tonga (Tongatapu)",              region: "S. Pacific",   latitude: -21.2, longitude: -175.2),
        .init(id: "tonga_vavau",      name: "Tonga (Vavaʻu)",                 region: "S. Pacific",   latitude: -18.6, longitude: -174.0),
        .init(id: "cook_rarotonga",   name: "Cook Islands (Rarotonga)",       region: "S. Pacific",   latitude: -21.2, longitude: -159.8),
        .init(id: "cook_aitutaki",    name: "Cook Islands (Aitutaki)",        region: "S. Pacific",   latitude: -18.9, longitude: -159.8),
        .init(id: "niue",             name: "Niue",                           region: "S. Pacific",   latitude: -19.1, longitude: -169.9),
        .init(id: "fp_society",       name: "Society Islands (Moorea)",       region: "Polynesia",    latitude: -17.5, longitude: -149.8),
        .init(id: "fp_tuamotu",       name: "Tuamotu Archipelago",            region: "Polynesia",    latitude: -16.0, longitude: -145.0),
        .init(id: "fp_marquesas",     name: "Marquesas",                      region: "Polynesia",    latitude:  -9.8, longitude: -139.0),
        .init(id: "fp_gambier",       name: "Gambier Islands",                region: "Polynesia",    latitude: -23.1, longitude: -134.9),
        .init(id: "fp_austral",       name: "Austral Islands",                region: "Polynesia",    latitude: -23.4, longitude: -149.5),
        .init(id: "pitcairn",         name: "Pitcairn Islands",               region: "Polynesia",    latitude: -25.1, longitude: -130.1),
        .init(id: "easter_island",    name: "Rapa Nui (Easter Island)",       region: "Polynesia",    latitude: -27.1, longitude: -109.4),
        .init(id: "fiji_n",           name: "Fiji – Vanua Levu",              region: "S. Pacific",   latitude: -16.6, longitude: 179.4),
        .init(id: "fiji_s",           name: "Fiji – Viti Levu",               region: "S. Pacific",   latitude: -17.8, longitude: 178.2),
        .init(id: "vanuatu",          name: "Vanuatu",                        region: "S. Pacific",   latitude: -16.3, longitude: 167.4),
        .init(id: "new_caledonia",    name: "New Caledonia",                  region: "S. Pacific",   latitude: -21.5, longitude: 165.5),
        .init(id: "solomon_islands",  name: "Solomon Islands",                region: "S. Pacific",   latitude:  -9.1, longitude: 159.5),
        .init(id: "png_bismarck",     name: "Papua New Guinea (Bismarck)",    region: "Melanesia",    latitude:  -4.5, longitude: 152.0),
        .init(id: "png_milne_bay",    name: "Papua New Guinea (Milne Bay)",   region: "Melanesia",    latitude: -10.5, longitude: 150.5),

        // ─── Southeast Asia (Coral Triangle) ──────────────────────────────────
        .init(id: "raja_ampat",       name: "Raja Ampat",                     region: "Indonesia",    latitude:  -0.5, longitude: 130.5),
        .init(id: "banda_sea",        name: "Banda Sea",                      region: "Indonesia",    latitude:  -5.5, longitude: 128.0),
        .init(id: "sulawesi",         name: "Wakatobi / SE Sulawesi",         region: "Indonesia",    latitude:  -5.5, longitude: 123.6),
        .init(id: "komodo",           name: "Komodo",                         region: "Indonesia",    latitude:  -8.6, longitude: 119.7),
        .init(id: "bali",             name: "Bali",                           region: "Indonesia",    latitude:  -8.5, longitude: 115.5),
        .init(id: "java_sea",         name: "Java Sea (Karimunjawa)",         region: "Indonesia",    latitude:  -5.8, longitude: 110.4),
        .init(id: "tubbataha",        name: "Tubbataha Reefs",                region: "Philippines",  latitude:   8.9, longitude: 119.9),
        .init(id: "visayas",          name: "Visayas (Bohol Sea)",            region: "Philippines",  latitude:   9.5, longitude: 123.8),
        .init(id: "palawan",          name: "Palawan",                        region: "Philippines",  latitude:  10.0, longitude: 119.0),
        .init(id: "sipadan",          name: "Sipadan / Sabah",                region: "Malaysia",     latitude:   4.1, longitude: 118.6),
        .init(id: "perhentian",       name: "Perhentian / Tioman",            region: "Malaysia",     latitude:   5.9, longitude: 102.7),
        .init(id: "andaman_th",       name: "Andaman Sea (Similan)",          region: "Thailand",     latitude:   8.6, longitude: 97.6),
        .init(id: "gulf_thailand",    name: "Gulf of Thailand (Tao)",         region: "Thailand",     latitude:  10.1, longitude: 99.8),
        .init(id: "phu_quoc",         name: "Phú Quốc",                       region: "Vietnam",      latitude:  10.2, longitude: 103.9),
        .init(id: "nha_trang",        name: "Nha Trang",                      region: "Vietnam",      latitude:  12.2, longitude: 109.3),
        .init(id: "mergui",           name: "Mergui Archipelago",             region: "Myanmar",      latitude:  12.0, longitude: 98.0),

        // ─── South & East China Seas, North Pacific ──────────────────────────
        .init(id: "spratly",          name: "Spratly Islands",                region: "S. China Sea", latitude:  10.0, longitude: 114.0),
        .init(id: "paracel",          name: "Paracel Islands",                region: "S. China Sea", latitude:  16.5, longitude: 112.0),
        .init(id: "hainan",           name: "Hainan",                         region: "China",        latitude:  18.3, longitude: 109.8),
        .init(id: "pratas",           name: "Pratas (Dongsha)",               region: "S. China Sea", latitude:  20.7, longitude: 116.7),
        .init(id: "taiwan_kenting",   name: "Kenting (Taiwan)",               region: "Taiwan",       latitude:  21.9, longitude: 120.8),
        .init(id: "okinawa",          name: "Okinawa",                        region: "Japan",        latitude:  26.5, longitude: 128.0),
        .init(id: "yaeyama",          name: "Yaeyama / Ishigaki",             region: "Japan",        latitude:  24.3, longitude: 124.1),
        .init(id: "ogasawara",        name: "Ogasawara (Bonin) Islands",      region: "Japan",        latitude:  27.1, longitude: 142.2),

        // ─── Indian Ocean ────────────────────────────────────────────────────
        .init(id: "maldives_n",       name: "Maldives – North",               region: "Indian Ocean", latitude:   6.5, longitude: 73.0),
        .init(id: "maldives_c",       name: "Maldives – Central",             region: "Indian Ocean", latitude:   3.2, longitude: 73.2),
        .init(id: "maldives_s",       name: "Maldives – South",               region: "Indian Ocean", latitude:  -0.7, longitude: 73.2),
        .init(id: "sri_lanka",        name: "Sri Lanka (Pigeon I.)",          region: "Indian Ocean", latitude:   8.7, longitude: 81.2),
        .init(id: "lakshadweep",      name: "Lakshadweep",                    region: "Indian Ocean", latitude:  10.6, longitude: 72.6),
        .init(id: "andaman_in",       name: "Andaman & Nicobar",              region: "Indian Ocean", latitude:  11.7, longitude: 92.7),
        .init(id: "gulf_mannar",      name: "Gulf of Mannar",                 region: "Indian Ocean", latitude:   9.0, longitude: 79.2),
        .init(id: "chagos",           name: "Chagos Archipelago",             region: "Indian Ocean", latitude:  -6.0, longitude: 71.5),
        .init(id: "seychelles_inner", name: "Seychelles – Inner Islands",     region: "Indian Ocean", latitude:  -4.6, longitude: 55.5),
        .init(id: "aldabra",          name: "Aldabra",                        region: "Indian Ocean", latitude:  -9.4, longitude: 46.4),
        .init(id: "mauritius",        name: "Mauritius",                      region: "Indian Ocean", latitude: -20.3, longitude: 57.6),
        .init(id: "rodrigues",        name: "Rodrigues",                      region: "Indian Ocean", latitude: -19.7, longitude: 63.4),
        .init(id: "reunion",          name: "Réunion",                        region: "Indian Ocean", latitude: -21.1, longitude: 55.5),
        .init(id: "mayotte",          name: "Mayotte",                        region: "Indian Ocean", latitude: -12.8, longitude: 45.2),
        .init(id: "comoros",          name: "Comoros",                        region: "Indian Ocean", latitude: -11.9, longitude: 43.4),
        .init(id: "madagascar_nw",    name: "Madagascar – NW (Nosy Be)",      region: "Indian Ocean", latitude: -13.4, longitude: 48.3),
        .init(id: "madagascar_sw",    name: "Madagascar – SW (Toliara)",      region: "Indian Ocean", latitude: -23.4, longitude: 43.7),
        .init(id: "mozambique_n",     name: "Quirimbas (Mozambique)",         region: "E. Africa",    latitude: -12.5, longitude: 40.5),
        .init(id: "mozambique_s",     name: "Bazaruto (Mozambique)",          region: "E. Africa",    latitude: -21.7, longitude: 35.5),
        .init(id: "tanzania",         name: "Zanzibar / Mafia",               region: "E. Africa",    latitude:  -7.5, longitude: 39.6),
        .init(id: "kenya",            name: "Kenya (Watamu)",                 region: "E. Africa",    latitude:  -3.4, longitude: 40.0),

        // ─── Red Sea & Arabia ────────────────────────────────────────────────
        .init(id: "red_sea_north",    name: "Red Sea – North (Sinai)",        region: "Middle East",  latitude:  27.5, longitude: 34.5),
        .init(id: "red_sea_central",  name: "Red Sea – Central (Hurghada)",   region: "Middle East",  latitude:  27.2, longitude: 33.9),
        .init(id: "red_sea_south",    name: "Red Sea – South (Sudan)",        region: "Middle East",  latitude:  19.6, longitude: 37.2),
        .init(id: "red_sea_saudi",    name: "Red Sea – Saudi Coast",          region: "Middle East",  latitude:  22.0, longitude: 38.8),
        .init(id: "socotra",          name: "Socotra",                        region: "Middle East",  latitude:  12.5, longitude: 53.9),
        .init(id: "oman",             name: "Oman (Musandam)",                region: "Middle East",  latitude:  26.2, longitude: 56.3),
        .init(id: "arabian_gulf",     name: "Arabian Gulf (UAE)",             region: "Middle East",  latitude:  24.5, longitude: 53.0),

        // ─── Caribbean ───────────────────────────────────────────────────────
        .init(id: "bermuda",          name: "Bermuda",                        region: "N. Atlantic",  latitude:  32.4, longitude: -64.8),
        .init(id: "bahamas_andros",   name: "Bahamas – Andros",               region: "Caribbean",    latitude:  24.5, longitude: -77.8),
        .init(id: "bahamas_exuma",    name: "Bahamas – Exuma",                region: "Caribbean",    latitude:  24.2, longitude: -76.6),
        .init(id: "cuba_jardines",    name: "Jardines de la Reina (Cuba)",    region: "Caribbean",    latitude:  20.8, longitude: -78.9),
        .init(id: "cayman",           name: "Cayman Islands",                 region: "Caribbean",    latitude:  19.3, longitude: -81.2),
        .init(id: "jamaica",          name: "Jamaica",                        region: "Caribbean",    latitude:  18.2, longitude: -77.5),
        .init(id: "dominican_rep",    name: "Dominican Republic",             region: "Caribbean",    latitude:  19.7, longitude: -70.0),
        .init(id: "puerto_rico",      name: "Puerto Rico",                    region: "Caribbean",    latitude:  18.0, longitude: -66.5),
        .init(id: "usvi",             name: "U.S. Virgin Islands",            region: "Caribbean",    latitude:  18.3, longitude: -64.9),
        .init(id: "bvi",              name: "British Virgin Islands",         region: "Caribbean",    latitude:  18.4, longitude: -64.6),
        .init(id: "anguilla_stmartin",name: "Anguilla / St. Martin",          region: "Caribbean",    latitude:  18.2, longitude: -63.1),
        .init(id: "antigua",          name: "Antigua & Barbuda",              region: "Caribbean",    latitude:  17.1, longitude: -61.8),
        .init(id: "guadeloupe",       name: "Guadeloupe",                     region: "Caribbean",    latitude:  16.2, longitude: -61.5),
        .init(id: "dominica",         name: "Dominica",                       region: "Caribbean",    latitude:  15.4, longitude: -61.4),
        .init(id: "martinique",       name: "Martinique",                     region: "Caribbean",    latitude:  14.6, longitude: -61.0),
        .init(id: "st_lucia",         name: "Saint Lucia",                    region: "Caribbean",    latitude:  13.9, longitude: -61.0),
        .init(id: "st_vincent",       name: "St. Vincent & Grenadines",       region: "Caribbean",    latitude:  13.0, longitude: -61.2),
        .init(id: "barbados",         name: "Barbados",                       region: "Caribbean",    latitude:  13.2, longitude: -59.5),
        .init(id: "grenada",          name: "Grenada",                        region: "Caribbean",    latitude:  12.1, longitude: -61.7),
        .init(id: "tobago",           name: "Tobago",                         region: "Caribbean",    latitude:  11.2, longitude: -60.7),
        .init(id: "bonaire",          name: "Bonaire",                        region: "Caribbean",    latitude:  12.2, longitude: -68.4),
        .init(id: "curacao",          name: "Curaçao",                        region: "Caribbean",    latitude:  12.2, longitude: -69.0),
        .init(id: "aruba",            name: "Aruba",                          region: "Caribbean",    latitude:  12.5, longitude: -70.0),
        .init(id: "los_roques",       name: "Los Roques (Venezuela)",         region: "Caribbean",    latitude:  11.8, longitude: -66.7),
        .init(id: "san_andres",       name: "San Andrés (Colombia)",          region: "Caribbean",    latitude:  12.5, longitude: -81.7),
        .init(id: "san_blas",         name: "Guna Yala / San Blas (Panama)",  region: "Caribbean",    latitude:   9.6, longitude: -78.7),
        .init(id: "costa_rica_carib", name: "Costa Rica – Caribbean",         region: "Caribbean",    latitude:   9.7, longitude: -82.7),
        .init(id: "honduras_bay",     name: "Bay Islands (Honduras)",         region: "Caribbean",    latitude:  16.3, longitude: -86.5),
        .init(id: "belize",           name: "Belize Barrier Reef",            region: "Caribbean",    latitude:  17.0, longitude: -88.0),
        .init(id: "mexico_yucatan",   name: "Mexican Caribbean (Cozumel)",    region: "Caribbean",    latitude:  20.4, longitude: -86.9),
        .init(id: "florida_keys",     name: "Florida Keys",                   region: "USA",          latitude:  24.7, longitude: -81.0),
        .init(id: "dry_tortugas",     name: "Dry Tortugas",                   region: "USA",          latitude:  24.6, longitude: -82.9),

        // ─── Eastern Pacific ─────────────────────────────────────────────────
        .init(id: "galapagos",        name: "Galápagos",                      region: "E. Pacific",   latitude:  -0.5, longitude: -90.5),
        .init(id: "cocos_cr",         name: "Cocos Island (Costa Rica)",      region: "E. Pacific",   latitude:   5.5, longitude: -87.0),
        .init(id: "clipperton",       name: "Clipperton",                     region: "E. Pacific",   latitude:  10.3, longitude: -109.2),
        .init(id: "revillagigedo",    name: "Revillagigedo",                  region: "E. Pacific",   latitude:  18.8, longitude: -112.0),
        .init(id: "malpelo",          name: "Malpelo (Colombia)",             region: "E. Pacific",   latitude:   4.0, longitude: -81.6),
        .init(id: "panama_pacific",   name: "Coiba (Panama Pacific)",         region: "E. Pacific",   latitude:   7.5, longitude: -81.7),
        .init(id: "mex_pacific",      name: "Huatulco (Mex. Pacific)",        region: "E. Pacific",   latitude:  15.7, longitude: -96.1),

        // ─── Tropical Atlantic ───────────────────────────────────────────────
        .init(id: "fernando_noronha", name: "Fernando de Noronha",            region: "Brazil",       latitude:  -3.9, longitude: -32.4),
        .init(id: "rocas_atoll",      name: "Atol das Rocas",                 region: "Brazil",       latitude:  -3.9, longitude: -33.8),
        .init(id: "abrolhos",         name: "Abrolhos Bank",                  region: "Brazil",       latitude: -18.0, longitude: -38.7),
        .init(id: "costa_corais",     name: "Costa dos Corais",               region: "Brazil",       latitude:  -9.2, longitude: -35.3),
        .init(id: "cape_verde",       name: "Cape Verde",                     region: "E. Atlantic",  latitude:  16.0, longitude: -24.0),
        .init(id: "sao_tome",         name: "São Tomé & Príncipe",            region: "E. Atlantic",  latitude:   1.6, longitude: 7.4),
        .init(id: "ascension",        name: "Ascension Island",               region: "S. Atlantic",  latitude:  -7.9, longitude: -14.4)
    ]

    /// Curated "tier 1" subset shown first while the rest stream in the background.
    /// Chosen to cover every major coral biogeographic region with the most
    /// ecologically and economically prominent reef in each. Roughly mirrors
    /// the headline sites in NOAA Coral Reef Watch's automated alert dashboards.
    static let priorityIDs: Set<String> = [
        // Australia & Coral Sea
        "gbr_north", "gbr_central", "gbr_south", "coral_sea_osprey", "ningaloo", "lord_howe",
        // Pacific
        "hawaii_main", "papahanaumokuakea", "samoa", "palau", "fiji_s", "new_caledonia",
        "fp_society", "tubbataha",
        // SE Asia / Coral Triangle
        "raja_ampat", "komodo",
        // Indian Ocean & Red Sea
        "maldives_c", "chagos", "seychelles_inner", "aldabra", "red_sea_central",
        // Caribbean & Atlantic
        "florida_keys", "belize", "puerto_rico", "honduras_bay",
        // Eastern Pacific
        "galapagos",
        // South Atlantic
        "abrolhos"
    ]

    /// NOAA's published Regional Virtual Stations catalog (214 sites).
    /// Each entry's time series is fetched from NOAA's per-station text file
    /// at `coralreefwatch.noaa.gov/product/vs/data/{rawID}.txt`. Coordinates
    /// are the polygon centers from each file's header. Names are NOAA's
    /// official labels.
    static let vsStations: [VirtualStation] = [
        .init(id: "abrolhos_reefs"         , name: "Abrolhos Reefs, Brazil"          , region: "Tropical Atlantic", latitude:  -17.225, longitude:   -39.000, source: .regionalVirtualStations),
        .init(id: "aden"                   , name: "Aden, Yemen"                     , region: "Red Sea / Arabia" , latitude:   12.775, longitude:    44.925, source: .regionalVirtualStations),
        .init(id: "madinah_makkah"         , name: "Al Madinah and Makkah"           , region: "Red Sea / Arabia" , latitude:   21.125, longitude:    39.450, source: .regionalVirtualStations),
        .init(id: "al_wusta"               , name: "Al Wusta, Oman"                  , region: "Indian Ocean"     , latitude:   19.625, longitude:    57.900, source: .regionalVirtualStations),
        .init(id: "andaman"                , name: "Andaman, India"                  , region: "Indian Ocean"     , latitude:   12.725, longitude:    93.150, source: .regionalVirtualStations),
        .init(id: "abc_islands"            , name: "Aruba, Curacao, and Bonaire"     , region: "Caribbean"        , latitude:   12.300, longitude:   -69.125, source: .regionalVirtualStations),
        .init(id: "austral_islands"        , name: "Austral Islands"                 , region: "Pacific Islands"  , latitude:  -24.825, longitude:  -149.100, source: .regionalVirtualStations),
        .init(id: "bahrain"                , name: "Bahrain"                         , region: "Persian Gulf"     , latitude:   26.125, longitude:    50.750, source: .regionalVirtualStations),
        .init(id: "bangka_belitung"        , name: "Bangka-Belitung Islands"         , region: "Indian Ocean"     , latitude:   -2.300, longitude:   107.000, source: .regionalVirtualStations),
        .init(id: "bassas_da_india"        , name: "Bassas da India, France"         , region: "Indian Ocean"     , latitude:  -21.900, longitude:    40.025, source: .regionalVirtualStations),
        .init(id: "beagle_gulf"            , name: "Beagle Gulf"                     , region: "SE Asia"          , latitude:  -12.775, longitude:   130.425, source: .regionalVirtualStations),
        .init(id: "belize"                 , name: "Belize"                          , region: "Caribbean"        , latitude:   17.025, longitude:   -88.075, source: .regionalVirtualStations),
        .init(id: "bermuda"                , name: "Bermuda"                         , region: "Other"            , latitude:   32.350, longitude:   -64.825, source: .regionalVirtualStations),
        .init(id: "brunei_darussalam"      , name: "Brunei Darussalam"               , region: "SE Asia"          , latitude:    5.025, longitude:   114.675, source: .regionalVirtualStations),
        .init(id: "buzios"                 , name: "Buzios, Brazil"                  , region: "Tropical Atlantic", latitude:  -22.725, longitude:   -41.800, source: .regionalVirtualStations),
        .init(id: "cape_verde"             , name: "Cape Verde Islands"              , region: "Tropical Atlantic", latitude:   15.975, longitude:   -24.025, source: .regionalVirtualStations),
        .init(id: "cayman_islands"         , name: "Cayman Islands"                  , region: "Caribbean"        , latitude:   19.500, longitude:   -80.575, source: .regionalVirtualStations),
        .init(id: "central_bahamas"        , name: "Central Bahamas"                 , region: "Caribbean"        , latitude:   23.900, longitude:   -77.425, source: .regionalVirtualStations),
        .init(id: "gbr_central"            , name: "Central GBR"                     , region: "Australia"        , latitude:  -19.225, longitude:   148.275, source: .regionalVirtualStations),
        .init(id: "central_mozambique"     , name: "Central Mozambique"              , region: "Indian Ocean"     , latitude:  -16.200, longitude:    39.550, source: .regionalVirtualStations),
        .init(id: "central_philippines"    , name: "Central Philippines"             , region: "SE Asia"          , latitude:   13.950, longitude:   122.225, source: .regionalVirtualStations),
        .init(id: "sulawesi_gorontalo"     , name: "Central Sulawesi and Gorontalo"  , region: "SE Asia"          , latitude:   -1.050, longitude:   123.025, source: .regionalVirtualStations),
        .init(id: "central_western_aus"    , name: "Central Western Australia"       , region: "Australia"        , latitude:  -20.700, longitude:   116.900, source: .regionalVirtualStations),
        .init(id: "chagos_archipelago"     , name: "Chagos Archipelago, UK"          , region: "Indian Ocean"     , latitude:   -6.200, longitude:    71.750, source: .regionalVirtualStations),
        .init(id: "chesterfield_islands"   , name: "Chesterfield Islands"            , region: "Australia"        , latitude:  -20.400, longitude:   158.900, source: .regionalVirtualStations),
        .init(id: "christmas_island"       , name: "Christmas Island, Australia"     , region: "Indian Ocean"     , latitude:  -10.375, longitude:   105.575, source: .regionalVirtualStations),
        .init(id: "clipperton_island"      , name: "Clipperton Island, France"       , region: "Eastern Pacific"  , latitude:   10.300, longitude:  -109.200, source: .regionalVirtualStations),
        .init(id: "colombia_atlantic"      , name: "Colombia Atlantic"               , region: "Caribbean"        , latitude:    9.925, longitude:   -75.525, source: .regionalVirtualStations),
        .init(id: "comoros"                , name: "Comoros"                         , region: "Indian Ocean"     , latitude:  -11.900, longitude:    43.800, source: .regionalVirtualStations),
        .init(id: "costa_rica_atlantic"    , name: "Costa Rica Atlantic"             , region: "Caribbean"        , latitude:    9.900, longitude:   -82.850, source: .regionalVirtualStations),
        .init(id: "costa_rica_pacific"     , name: "Costa Rica Pacific"              , region: "Caribbean"        , latitude:    9.500, longitude:   -84.425, source: .regionalVirtualStations),
        .init(id: "costa_dos_corais"       , name: "Costa dos Corais, Brazil"        , region: "Tropical Atlantic", latitude:   -9.250, longitude:   -35.525, source: .regionalVirtualStations),
        .init(id: "dhofar"                 , name: "Dhofar, Oman"                    , region: "Indian Ocean"     , latitude:   17.375, longitude:    55.500, source: .regionalVirtualStations),
        .init(id: "dongsha"                , name: "Dongsha, Taiwan"                 , region: "SE Asia"          , latitude:   20.975, longitude:   116.225, source: .regionalVirtualStations),
        .init(id: "east_java_bali"         , name: "East Java and Bali"              , region: "SE Asia"          , latitude:   -6.950, longitude:   114.100, source: .regionalVirtualStations),
        .init(id: "east_kalimantan"        , name: "East Kalimantan"                 , region: "SE Asia"          , latitude:    0.625, longitude:   117.925, source: .regionalVirtualStations),
        .init(id: "east_nusa_tenggara"     , name: "East Nusa Tenggara"              , region: "SE Asia"          , latitude:   -9.325, longitude:   122.050, source: .regionalVirtualStations),
        .init(id: "easter_island"          , name: "Easter Island, Chile"            , region: "Other"            , latitude:  -27.175, longitude:  -109.325, source: .regionalVirtualStations),
        .init(id: "eastern_fsm"            , name: "Eastern FSM"                     , region: "Pacific Islands"  , latitude:    5.150, longitude:   153.000, source: .regionalVirtualStations),
        .init(id: "east_gulf_of_thailand"  , name: "Eastern Gulf of Thailand"        , region: "Indian Ocean"     , latitude:   11.250, longitude:   102.500, source: .regionalVirtualStations),
        .init(id: "eastern_new_caledonia"  , name: "Eastern New Caledonia"           , region: "Pacific Islands"  , latitude:  -20.750, longitude:   165.975, source: .regionalVirtualStations),
        .init(id: "eastern_persian_gulf"   , name: "Eastern Persian Gulf"            , region: "Persian Gulf"     , latitude:   25.925, longitude:    54.050, source: .regionalVirtualStations),
        .init(id: "eastern_philippines"    , name: "Eastern Philippines"             , region: "SE Asia"          , latitude:   10.950, longitude:   123.900, source: .regionalVirtualStations),
        .init(id: "eastern_sri_lanka"      , name: "Eastern Sri Lanka"               , region: "Indian Ocean"     , latitude:    8.075, longitude:    81.575, source: .regionalVirtualStations),
        .init(id: "eastern_yemen"          , name: "Eastern Yemen"                   , region: "Red Sea / Arabia" , latitude:   14.475, longitude:    49.675, source: .regionalVirtualStations),
        .init(id: "egypt"                  , name: "Egypt"                           , region: "Red Sea / Arabia" , latitude:   24.325, longitude:    35.575, source: .regionalVirtualStations),
        .init(id: "el_salvador"            , name: "El Salvador"                     , region: "Caribbean"        , latitude:   13.175, longitude:   -87.750, source: .regionalVirtualStations),
        .init(id: "eritrea"                , name: "Eritrea"                         , region: "Red Sea / Arabia" , latitude:   15.525, longitude:    40.750, source: .regionalVirtualStations),
        .init(id: "gbr_far_northern"       , name: "Far Northern GBR"                , region: "Australia"        , latitude:  -12.675, longitude:   144.100, source: .regionalVirtualStations),
        .init(id: "fernando_de_noronha"    , name: "Fernando de Noronha, Brazil"     , region: "Tropical Atlantic", latitude:   -3.875, longitude:   -33.100, source: .regionalVirtualStations),
        .init(id: "fiji"                   , name: "Fiji"                            , region: "Pacific Islands"  , latitude:  -16.775, longitude:   179.350, source: .regionalVirtualStations),
        .init(id: "florida_keys"           , name: "Florida Keys"                    , region: "Caribbean"        , latitude:   24.750, longitude:   -81.625, source: .regionalVirtualStations),
        .init(id: "flower_garden"          , name: "Flower Garden Banks, Texas"      , region: "Caribbean"        , latitude:   28.050, longitude:   -93.975, source: .regionalVirtualStations),
        .init(id: "galapagos"              , name: "Galapagos, Ecuador"              , region: "Eastern Pacific"  , latitude:    0.150, longitude:   -90.625, source: .regionalVirtualStations),
        .init(id: "gilbert_islands"        , name: "Gilbert Islands, Kiribati"       , region: "Pacific Islands"  , latitude:    0.350, longitude:   173.200, source: .regionalVirtualStations),
        .init(id: "glorieuse_geyser"       , name: "Glorioso Islands"                , region: "Indian Ocean"     , latitude:  -11.975, longitude:    46.775, source: .regionalVirtualStations),
        .init(id: "great_nicobar"          , name: "Great Nicobar, India"            , region: "Indian Ocean"     , latitude:    8.025, longitude:    93.325, source: .regionalVirtualStations),
        .init(id: "guam"                   , name: "Guam"                            , region: "Pacific Islands"  , latitude:   13.150, longitude:   144.625, source: .regionalVirtualStations),
        .init(id: "gulf_of_aqaba"          , name: "Gulf of Aqaba"                   , region: "Red Sea / Arabia" , latitude:   28.600, longitude:    34.625, source: .regionalVirtualStations),
        .init(id: "gulf_of_carpentaria"    , name: "Gulf of Carpentaria"             , region: "SE Asia"          , latitude:  -14.500, longitude:   138.850, source: .regionalVirtualStations),
        .init(id: "gulf_of_kutch"          , name: "Gulf of Kutch, India"            , region: "Indian Ocean"     , latitude:   22.225, longitude:    69.575, source: .regionalVirtualStations),
        .init(id: "gulf_of_mannar"         , name: "Gulf of Mannar"                  , region: "Indian Ocean"     , latitude:    8.850, longitude:    78.975, source: .regionalVirtualStations),
        .init(id: "gulf_of_oman"           , name: "Gulf of Oman"                    , region: "Indian Ocean"     , latitude:   24.100, longitude:    58.500, source: .regionalVirtualStations),
        .init(id: "gulf_of_suez"           , name: "Gulf of Suez"                    , region: "Red Sea / Arabia" , latitude:   28.400, longitude:    33.350, source: .regionalVirtualStations),
        .init(id: "gulf_of_tadjoura"       , name: "Gulf of Tadjoura, Djubouti"      , region: "Red Sea / Arabia" , latitude:   11.775, longitude:    43.300, source: .regionalVirtualStations),
        .init(id: "hainan_island"          , name: "Hainan Island, China"            , region: "Indian Ocean"     , latitude:   19.125, longitude:   109.850, source: .regionalVirtualStations),
        .init(id: "hamelin_pool"           , name: "Hamelin Pool"                    , region: "Australia"        , latitude:  -26.100, longitude:   113.950, source: .regionalVirtualStations),
        .init(id: "honduras"               , name: "Honduras"                        , region: "Caribbean"        , latitude:   16.700, longitude:   -85.850, source: .regionalVirtualStations),
        .init(id: "hong_kong"              , name: "Hong Kong, China"                , region: "SE Asia"          , latitude:   22.250, longitude:   114.375, source: .regionalVirtualStations),
        .init(id: "houtman_abrolhos"       , name: "Houtman Abrolhos"                , region: "Australia"        , latitude:  -28.500, longitude:   113.850, source: .regionalVirtualStations),
        .init(id: "howland_baker"          , name: "Howland and Baker"               , region: "Pacific Islands"  , latitude:    0.500, longitude:  -176.525, source: .regionalVirtualStations),
        .init(id: "inhambane"              , name: "Inhambane, Mozambique"           , region: "Indian Ocean"     , latitude:  -23.000, longitude:    35.975, source: .regionalVirtualStations),
        .init(id: "isla_del_coco"          , name: "Isla del Coco, Costa Rica"       , region: "Eastern Pacific"  , latitude:    5.550, longitude:   -87.075, source: .regionalVirtualStations),
        .init(id: "jamaica"                , name: "Jamaica"                         , region: "Caribbean"        , latitude:   17.675, longitude:   -77.250, source: .regionalVirtualStations),
        .init(id: "jazan"                  , name: "Jazan, Saudi Arabia"             , region: "Red Sea / Arabia" , latitude:   17.175, longitude:    41.800, source: .regionalVirtualStations),
        .init(id: "johnston_atoll"         , name: "Johnston Atoll"                  , region: "Pacific Islands"  , latitude:   16.700, longitude:  -169.475, source: .regionalVirtualStations),
        .init(id: "johor_pahang"           , name: "Johor and Pahang, Malaysia"      , region: "Indian Ocean"     , latitude:    2.250, longitude:   104.200, source: .regionalVirtualStations),
        .init(id: "kenya"                  , name: "Kenya"                           , region: "Indian Ocean"     , latitude:   -3.200, longitude:    40.525, source: .regionalVirtualStations),
        .init(id: "kerala"                 , name: "Kerala, India"                   , region: "Indian Ocean"     , latitude:    9.900, longitude:    76.300, source: .regionalVirtualStations),
        .init(id: "la_guajira"             , name: "La Guajira, Colombia"            , region: "Caribbean"        , latitude:   12.075, longitude:   -71.925, source: .regionalVirtualStations),
        .init(id: "lakshadweep"            , name: "Lakshadweep, India"              , region: "Indian Ocean"     , latitude:   10.325, longitude:    72.875, source: .regionalVirtualStations),
        .init(id: "lampung_banten"         , name: "Lampung and Banten"              , region: "Indian Ocean"     , latitude:   -5.925, longitude:   105.075, source: .regionalVirtualStations),
        .init(id: "leeward_caribbean"      , name: "Leeward Caribbean Islands"       , region: "Caribbean"        , latitude:   16.775, longitude:   -62.325, source: .regionalVirtualStations),
        .init(id: "lord_howe_island"       , name: "Lord Howe Island, Australia"     , region: "Australia"        , latitude:  -31.275, longitude:   159.225, source: .regionalVirtualStations),
        .init(id: "hawaii"                 , name: "Main Hawaiian Islands"           , region: "Pacific Islands"  , latitude:   20.575, longitude:  -157.700, source: .regionalVirtualStations),
        .init(id: "malacca_strait"         , name: "Malacca Strait, Malaysia"        , region: "Indian Ocean"     , latitude:    3.225, longitude:   101.350, source: .regionalVirtualStations),
        .init(id: "maldives"               , name: "Maldives"                        , region: "Indian Ocean"     , latitude:    3.300, longitude:    72.950, source: .regionalVirtualStations),
        .init(id: "maluku"                 , name: "Maluku, Indonesia"               , region: "SE Asia"          , latitude:   -5.550, longitude:   130.425, source: .regionalVirtualStations),
        .init(id: "maputo"                 , name: "Maputo, Mozambique"              , region: "Indian Ocean"     , latitude:  -26.150, longitude:    33.275, source: .regionalVirtualStations),
        .init(id: "maracajau"              , name: "Maracajau, Brazil"               , region: "Tropical Atlantic", latitude:   -6.100, longitude:   -35.125, source: .regionalVirtualStations),
        .init(id: "marmion_rottnest"       , name: "Marmion and Rottnest Island"     , region: "Australia"        , latitude:  -31.925, longitude:   115.500, source: .regionalVirtualStations),
        .init(id: "marquesas_islands"      , name: "Marquesas Islands"               , region: "Pacific Islands"  , latitude:   -9.275, longitude:  -139.625, source: .regionalVirtualStations),
        .init(id: "marshall_islands"       , name: "Marshall Islands"                , region: "Pacific Islands"  , latitude:    8.450, longitude:   167.100, source: .regionalVirtualStations),
        .init(id: "mayotte"                , name: "Mayotte, France"                 , region: "Indian Ocean"     , latitude:  -12.925, longitude:    45.400, source: .regionalVirtualStations),
        .init(id: "moreton_bay"            , name: "Moreton Bay, Australia"          , region: "Australia"        , latitude:  -27.075, longitude:   153.575, source: .regionalVirtualStations),
        .init(id: "nauru"                  , name: "Nauru"                           , region: "Pacific Islands"  , latitude:   -0.525, longitude:   166.925, source: .regionalVirtualStations),
        .init(id: "nearshore_venezuela"    , name: "Nearshore Venezuela"             , region: "Caribbean"        , latitude:   10.625, longitude:   -66.275, source: .regionalVirtualStations),
        .init(id: "nicaragua"              , name: "Nicaragua"                       , region: "Caribbean"        , latitude:   14.125, longitude:   -81.750, source: .regionalVirtualStations),
        .init(id: "ningaloo"               , name: "Ningaloo"                        , region: "Australia"        , latitude:  -23.225, longitude:   113.900, source: .regionalVirtualStations),
        .init(id: "norfolk_island"         , name: "Norfolk Island, Australia"       , region: "Pacific Islands"  , latitude:  -29.050, longitude:   167.950, source: .regionalVirtualStations),
        .init(id: "north_maluku"           , name: "North Maluku, Indonesia"         , region: "SE Asia"          , latitude:    0.125, longitude:   126.700, source: .regionalVirtualStations),
        .init(id: "north_sulawesi"         , name: "North Sulawesi"                  , region: "SE Asia"          , latitude:    2.575, longitude:   125.075, source: .regionalVirtualStations),
        .init(id: "north_western_aus"      , name: "North Western Australia"         , region: "Australia"        , latitude:  -15.750, longitude:   124.775, source: .regionalVirtualStations),
        .init(id: "northeastern_cuba"      , name: "Northeastern Cuba"               , region: "Caribbean"        , latitude:   21.225, longitude:   -75.925, source: .regionalVirtualStations),
        .init(id: "northeastern_madagascar", name: "Northeastern Madagascar"         , region: "Indian Ocean"     , latitude:  -15.325, longitude:    49.875, source: .regionalVirtualStations),
        .init(id: "northern_bahamas"       , name: "Northern Bahamas"                , region: "Caribbean"        , latitude:   26.500, longitude:   -77.950, source: .regionalVirtualStations),
        .init(id: "northern_borneo"        , name: "Northern Borneo, Malaysia"       , region: "SE Asia"          , latitude:    3.850, longitude:   113.425, source: .regionalVirtualStations),
        .init(id: "northern_cook_islands"  , name: "Northern Cook Islands"           , region: "Pacific Islands"  , latitude:  -10.950, longitude:  -165.200, source: .regionalVirtualStations),
        .init(id: "northern_coral_sea"     , name: "Northern Coral Sea Islands"      , region: "Australia"        , latitude:  -16.000, longitude:   149.350, source: .regionalVirtualStations),
        .init(id: "gbr_northern"           , name: "Northern GBR"                    , region: "Australia"        , latitude:  -16.100, longitude:   145.975, source: .regionalVirtualStations),
        .init(id: "northern_hispaniola"    , name: "Northern Hispaniola"             , region: "Caribbean"        , latitude:   19.325, longitude:   -70.675, source: .regionalVirtualStations),
        .init(id: "northern_java"          , name: "Northern Java"                   , region: "Indian Ocean"     , latitude:   -6.225, longitude:   109.525, source: .regionalVirtualStations),
        .init(id: "northern_line_islands"  , name: "Northern Line Islands"           , region: "Pacific Islands"  , latitude:    3.025, longitude:  -159.800, source: .regionalVirtualStations),
        .init(id: "northern_cnmi"          , name: "Northern Mariana Islands"        , region: "Pacific Islands"  , latitude:   17.250, longitude:   145.550, source: .regionalVirtualStations),
        .init(id: "northern_mauritius"     , name: "Northern Mauritius"              , region: "Indian Ocean"     , latitude:  -10.575, longitude:    58.675, source: .regionalVirtualStations),
        .init(id: "northern_mozambique"    , name: "Northern Mozambique"             , region: "Indian Ocean"     , latitude:  -12.625, longitude:    41.000, source: .regionalVirtualStations),
        .init(id: "northern_myanmar"       , name: "Northern Myanmar"                , region: "Indian Ocean"     , latitude:   18.150, longitude:    93.500, source: .regionalVirtualStations),
        .init(id: "northern_philippines"   , name: "Northern Philippines"            , region: "SE Asia"          , latitude:   17.750, longitude:   121.125, source: .regionalVirtualStations),
        .init(id: "northern_ryukyu_islands", name: "Northern Ryukyu Islands, Japan"  , region: "Other"            , latitude:   28.300, longitude:   129.000, source: .regionalVirtualStations),
        .init(id: "northern_taiwan"        , name: "Northern Taiwan"                 , region: "Other"            , latitude:   25.100, longitude:   121.725, source: .regionalVirtualStations),
        .init(id: "northern_territory"     , name: "Northern Territory"              , region: "SE Asia"          , latitude:  -10.975, longitude:   134.300, source: .regionalVirtualStations),
        .init(id: "northern_tonga"         , name: "Northern Tonga"                  , region: "Pacific Islands"  , latitude:  -15.800, longitude:  -175.200, source: .regionalVirtualStations),
        .init(id: "northern_vietnam"       , name: "Northern Vietnam"                , region: "Indian Ocean"     , latitude:   18.100, longitude:   107.475, source: .regionalVirtualStations),
        .init(id: "northwestern_cuba"      , name: "Northwestern Cuba"               , region: "Caribbean"        , latitude:   22.650, longitude:   -81.275, source: .regionalVirtualStations),
        .init(id: "nwhi"                   , name: "Northwestern Hawaiian Islands"   , region: "Pacific Islands"  , latitude:   25.675, longitude:  -170.125, source: .regionalVirtualStations),
        .init(id: "northwestern_madagascar", name: "Northwestern Madagascar"         , region: "Indian Ocean"     , latitude:  -14.050, longitude:    46.800, source: .regionalVirtualStations),
        .init(id: "northwestern_sumatra"   , name: "Northwestern Sumatra"            , region: "Indian Ocean"     , latitude:    2.950, longitude:    97.225, source: .regionalVirtualStations),
        .init(id: "offshore_venezuela"     , name: "Offshore Venezuela"              , region: "Caribbean"        , latitude:   11.425, longitude:   -65.350, source: .regionalVirtualStations),
        .init(id: "ogasawara"              , name: "Ogasawara Islands"               , region: "Pacific Islands"  , latitude:   27.125, longitude:   142.175, source: .regionalVirtualStations),
        .init(id: "palau"                  , name: "Palau"                           , region: "SE Asia"          , latitude:    7.675, longitude:   134.425, source: .regionalVirtualStations),
        .init(id: "panama_atlantic_east"   , name: "Panama Atlantic East"            , region: "Caribbean"        , latitude:    9.200, longitude:   -78.700, source: .regionalVirtualStations),
        .init(id: "panama_atlantic_west"   , name: "Panama Atlantic West"            , region: "Caribbean"        , latitude:    9.200, longitude:   -81.650, source: .regionalVirtualStations),
        .init(id: "panama_pacific_east"    , name: "Panama Pacific East"             , region: "Caribbean"        , latitude:    8.175, longitude:   -79.325, source: .regionalVirtualStations),
        .init(id: "panama_pacific_west"    , name: "Panama Pacific West"             , region: "Eastern Pacific"  , latitude:    7.725, longitude:   -82.250, source: .regionalVirtualStations),
        .init(id: "papua_new_guinea"       , name: "Papua New Guinea"                , region: "Pacific Islands"  , latitude:   -6.425, longitude:   151.150, source: .regionalVirtualStations),
        .init(id: "paracel_islands"        , name: "Paracel Islands, China"          , region: "SE Asia"          , latitude:   16.450, longitude:   112.025, source: .regionalVirtualStations),
        .init(id: "phoenix_islands"        , name: "Phoenix Islands, Kiribati"       , region: "Pacific Islands"  , latitude:   -3.150, longitude:  -172.825, source: .regionalVirtualStations),
        .init(id: "pitcairn"               , name: "Pitcairn Islands"                , region: "Other"            , latitude:  -24.350, longitude:  -129.575, source: .regionalVirtualStations),
        .init(id: "puerto_rico"            , name: "Puerto Rico"                     , region: "Caribbean"        , latitude:   18.200, longitude:   -66.625, source: .regionalVirtualStations),
        .init(id: "pulu_keeling"           , name: "Pulu Keeling, Australia"         , region: "Indian Ocean"     , latitude:  -12.025, longitude:    96.900, source: .regionalVirtualStations),
        .init(id: "quintana_roo"           , name: "Quintana Roo, Mexico"            , region: "Caribbean"        , latitude:   19.925, longitude:   -87.400, source: .regionalVirtualStations),
        .init(id: "riau_islands"           , name: "Riau Islands"                    , region: "Indian Ocean"     , latitude:    2.475, longitude:   107.400, source: .regionalVirtualStations),
        .init(id: "rowley_shoals"          , name: "Rowley Shoals"                   , region: "Australia"        , latitude:  -17.325, longitude:   119.250, source: .regionalVirtualStations),
        .init(id: "sabah"                  , name: "Sabah, Malaysia"                 , region: "SE Asia"          , latitude:    5.800, longitude:   117.200, source: .regionalVirtualStations),
        .init(id: "samoas"                 , name: "Samoas"                          , region: "Pacific Islands"  , latitude:  -12.825, longitude:  -170.475, source: .regionalVirtualStations),
        .init(id: "sao_tome_principe"      , name: "Sao Tome and Principe"           , region: "Tropical Atlantic", latitude:    0.825, longitude:     6.950, source: .regionalVirtualStations),
        .init(id: "scott_ashmore"          , name: "Scott to Ashmore Reefs"          , region: "SE Asia"          , latitude:  -13.475, longitude:   122.625, source: .regionalVirtualStations),
        .init(id: "seychelles"             , name: "Seychelles"                      , region: "Indian Ocean"     , latitude:   -7.000, longitude:    51.325, source: .regionalVirtualStations),
        .init(id: "shark_bay"              , name: "Shark Bay"                       , region: "Australia"        , latitude:  -25.475, longitude:   113.000, source: .regionalVirtualStations),
        .init(id: "singapore"              , name: "Singapore Strait"                , region: "Indian Ocean"     , latitude:    0.200, longitude:   104.150, source: .regionalVirtualStations),
        .init(id: "society_archipelago"    , name: "Society Archipelago"             , region: "Pacific Islands"  , latitude:  -16.950, longitude:  -151.375, source: .regionalVirtualStations),
        .init(id: "socotra"                , name: "Socotra, Yemen"                  , region: "Indian Ocean"     , latitude:   12.425, longitude:    53.250, source: .regionalVirtualStations),
        .init(id: "solomon_islands"        , name: "Solomon Islands"                 , region: "Pacific Islands"  , latitude:   -8.700, longitude:   162.175, source: .regionalVirtualStations),
        .init(id: "somalia"                , name: "Somalia"                         , region: "Indian Ocean"     , latitude:    0.575, longitude:    44.075, source: .regionalVirtualStations),
        .init(id: "south_africa"           , name: "South Africa"                    , region: "Indian Ocean"     , latitude:  -27.775, longitude:    32.725, source: .regionalVirtualStations),
        .init(id: "southeast_sulawesi"     , name: "South East Sulawesi"             , region: "SE Asia"          , latitude:   -5.000, longitude:   122.750, source: .regionalVirtualStations),
        .init(id: "south_sulawesi"         , name: "South Sulawesi"                  , region: "SE Asia"          , latitude:   -5.325, longitude:   119.625, source: .regionalVirtualStations),
        .init(id: "southeast_florida"      , name: "Southeast Florida"               , region: "Caribbean"        , latitude:   26.300, longitude:   -80.075, source: .regionalVirtualStations),
        .init(id: "southeastern_cuba"      , name: "Southeastern Cuba"               , region: "Caribbean"        , latitude:   20.675, longitude:   -77.025, source: .regionalVirtualStations),
        .init(id: "southeastern_india"     , name: "Southeastern India"              , region: "Indian Ocean"     , latitude:   11.700, longitude:    80.150, source: .regionalVirtualStations),
        .init(id: "southeastern_madagascar", name: "Southeastern Madagascar"         , region: "Indian Ocean"     , latitude:  -22.350, longitude:    47.750, source: .regionalVirtualStations),
        .init(id: "southern_borneo"        , name: "Southern Borneo"                 , region: "SE Asia"          , latitude:   -3.575, longitude:   116.550, source: .regionalVirtualStations),
        .init(id: "southern_cook_islands"  , name: "Southern Cook Islands"           , region: "Pacific Islands"  , latitude:  -19.975, longitude:  -163.625, source: .regionalVirtualStations),
        .init(id: "southern_coral_sea"     , name: "Southern Coral Sea Islands"      , region: "Australia"        , latitude:  -21.100, longitude:   153.975, source: .regionalVirtualStations),
        .init(id: "gbr_southern"           , name: "Southern GBR"                    , region: "Australia"        , latitude:  -22.625, longitude:   151.125, source: .regionalVirtualStations),
        .init(id: "southern_hispaniola"    , name: "Southern Hispaniola"             , region: "Caribbean"        , latitude:   18.650, longitude:   -71.775, source: .regionalVirtualStations),
        .init(id: "southern_java"          , name: "Southern Java"                   , region: "Indian Ocean"     , latitude:   -7.650, longitude:   108.400, source: .regionalVirtualStations),
        .init(id: "southern_line_islands"  , name: "Southern Line Islands"           , region: "Pacific Islands"  , latitude:   -7.700, longitude:  -153.075, source: .regionalVirtualStations),
        .init(id: "southern_mauritius"     , name: "Southern Mauritius"              , region: "Indian Ocean"     , latitude:  -18.750, longitude:    60.450, source: .regionalVirtualStations),
        .init(id: "southern_myanmar"       , name: "Southern Myanmar"                , region: "Indian Ocean"     , latitude:   12.175, longitude:    97.900, source: .regionalVirtualStations),
        .init(id: "southern_philippines"   , name: "Southern Philippines"            , region: "SE Asia"          , latitude:    7.400, longitude:   122.900, source: .regionalVirtualStations),
        .init(id: "southern_ryukyu_islands", name: "Southern Ryukyu Islands, Japan"  , region: "SE Asia"          , latitude:   24.975, longitude:   124.200, source: .regionalVirtualStations),
        .init(id: "southern_sri_lanka"     , name: "Southern Sri Lanka"              , region: "Indian Ocean"     , latitude:    6.300, longitude:    80.650, source: .regionalVirtualStations),
        .init(id: "southern_taiwan"        , name: "Southern Taiwan"                 , region: "SE Asia"          , latitude:   22.875, longitude:   120.550, source: .regionalVirtualStations),
        .init(id: "southern_tonga"         , name: "Southern Tonga"                  , region: "Pacific Islands"  , latitude:  -19.950, longitude:  -175.050, source: .regionalVirtualStations),
        .init(id: "southern_vietnam"       , name: "Southern Vietnam"                , region: "Indian Ocean"     , latitude:   11.300, longitude:   108.125, source: .regionalVirtualStations),
        .init(id: "southwestern_cuba"      , name: "Southwestern Cuba"               , region: "Caribbean"        , latitude:   21.750, longitude:   -82.475, source: .regionalVirtualStations),
        .init(id: "southwestern_madagascar", name: "Southwestern Madagascar"         , region: "Indian Ocean"     , latitude:  -22.675, longitude:    44.050, source: .regionalVirtualStations),
        .init(id: "southwestern_sumatra"   , name: "Southwestern Sumatra"            , region: "Indian Ocean"     , latitude:   -2.875, longitude:   100.400, source: .regionalVirtualStations),
        .init(id: "southwestern_thailand"  , name: "Southwestern Thailand"           , region: "Indian Ocean"     , latitude:    7.675, longitude:    98.875, source: .regionalVirtualStations),
        .init(id: "spratly_islands"        , name: "Spratly Islands"                 , region: "SE Asia"          , latitude:    7.950, longitude:   113.750, source: .regionalVirtualStations),
        .init(id: "sudan"                  , name: "Sudan"                           , region: "Red Sea / Arabia" , latitude:   20.400, longitude:    37.625, source: .regionalVirtualStations),
        .init(id: "tabuk"                  , name: "Tabuk, Saudi Arabia"             , region: "Red Sea / Arabia" , latitude:   26.000, longitude:    36.175, source: .regionalVirtualStations),
        .init(id: "tanzania"               , name: "Tanzania"                        , region: "Indian Ocean"     , latitude:   -7.575, longitude:    39.725, source: .regionalVirtualStations),
        .init(id: "terengganu"             , name: "Terengganu, Malaysia"            , region: "Indian Ocean"     , latitude:    5.375, longitude:   103.150, source: .regionalVirtualStations),
        .init(id: "timor_leste"            , name: "Timor-Leste"                     , region: "SE Asia"          , latitude:   -8.325, longitude:   127.225, source: .regionalVirtualStations),
        .init(id: "todos_os_santos"        , name: "Todos os Santos, Brazil"         , region: "Tropical Atlantic", latitude:  -13.375, longitude:   -38.375, source: .regionalVirtualStations),
        .init(id: "torres_strait"          , name: "Torres Strait"                   , region: "Pacific Islands"  , latitude:   -9.950, longitude:   143.650, source: .regionalVirtualStations),
        .init(id: "trinadade_martim_vaz"   , name: "Trinadade and Martim Vaz, Brazil", region: "Tropical Atlantic", latitude:  -20.475, longitude:   -29.125, source: .regionalVirtualStations),
        .init(id: "trinidad_tobago"        , name: "Trinidad and Tobago"             , region: "Caribbean"        , latitude:   10.875, longitude:   -60.725, source: .regionalVirtualStations),
        .init(id: "tromelin_reunion"       , name: "Tromelin and Reunion, France"    , region: "Indian Ocean"     , latitude:  -18.625, longitude:    54.975, source: .regionalVirtualStations),
        .init(id: "tuamotu_archipelago"    , name: "Tuamotu Archipelago"             , region: "Pacific Islands"  , latitude:  -18.975, longitude:  -141.500, source: .regionalVirtualStations),
        .init(id: "turks_caicos"           , name: "Turks and Caicos"                , region: "Caribbean"        , latitude:   22.000, longitude:   -72.725, source: .regionalVirtualStations),
        .init(id: "tuvalu"                 , name: "Tuvalu"                          , region: "Pacific Islands"  , latitude:   -7.525, longitude:   177.975, source: .regionalVirtualStations),
        .init(id: "vanuatu"                , name: "Vanuatu"                         , region: "Pacific Islands"  , latitude:  -16.650, longitude:   168.375, source: .regionalVirtualStations),
        .init(id: "veracruz"               , name: "Veracruz, Mexico"                , region: "Caribbean"        , latitude:   20.350, longitude:   -96.075, source: .regionalVirtualStations),
        .init(id: "usvi"                   , name: "Virgin Islands"                  , region: "Caribbean"        , latitude:   18.200, longitude:   -64.550, source: .regionalVirtualStations),
        .init(id: "wake_atoll"             , name: "Wake Atoll"                      , region: "Pacific Islands"  , latitude:   19.300, longitude:   166.800, source: .regionalVirtualStations),
        .init(id: "wallis_futuna"          , name: "Wallis and Futuna"               , region: "Pacific Islands"  , latitude:  -13.625, longitude:  -176.900, source: .regionalVirtualStations),
        .init(id: "west_kalimanta"         , name: "West Kalimantan"                 , region: "Indian Ocean"     , latitude:   -1.050, longitude:   109.375, source: .regionalVirtualStations),
        .init(id: "west_nusa_tenggara"     , name: "West Nusa Tenggara"              , region: "SE Asia"          , latitude:   -8.625, longitude:   117.625, source: .regionalVirtualStations),
        .init(id: "west_papua"             , name: "West Papua"                      , region: "SE Asia"          , latitude:   -1.625, longitude:   133.900, source: .regionalVirtualStations),
        .init(id: "west_sulawesi"          , name: "West Sulawesi"                   , region: "SE Asia"          , latitude:   -2.275, longitude:   119.075, source: .regionalVirtualStations),
        .init(id: "west_timor"             , name: "West Timor"                      , region: "SE Asia"          , latitude:   -9.925, longitude:   123.775, source: .regionalVirtualStations),
        .init(id: "western_fsm"            , name: "Western FSM"                     , region: "SE Asia"          , latitude:    9.100, longitude:   139.450, source: .regionalVirtualStations),
        .init(id: "west_gulf_of_thailand"  , name: "Western Gulf of Thailand"        , region: "Indian Ocean"     , latitude:   10.900, longitude:    99.750, source: .regionalVirtualStations),
        .init(id: "western_india"          , name: "Western India"                   , region: "Indian Ocean"     , latitude:   17.675, longitude:    72.200, source: .regionalVirtualStations),
        .init(id: "western_madagascar"     , name: "Western Madagascar"              , region: "Indian Ocean"     , latitude:  -17.450, longitude:    43.450, source: .regionalVirtualStations),
        .init(id: "western_new_caledonia"  , name: "Western New Caledonia"           , region: "Pacific Islands"  , latitude:  -21.025, longitude:   165.075, source: .regionalVirtualStations),
        .init(id: "western_persian_gulf"   , name: "Western Persian Gulf"            , region: "Red Sea / Arabia" , latitude:   28.325, longitude:    49.375, source: .regionalVirtualStations),
        .init(id: "western_philippines"    , name: "Western Philippines"             , region: "SE Asia"          , latitude:   10.500, longitude:   119.225, source: .regionalVirtualStations),
        .init(id: "western_yemen"          , name: "Western Yemen"                   , region: "Red Sea / Arabia" , latitude:   14.350, longitude:    42.600, source: .regionalVirtualStations),
        .init(id: "windward_caribbean"     , name: "Windward Caribbean Islands"      , region: "Caribbean"        , latitude:   13.400, longitude:   -60.475, source: .regionalVirtualStations),
        .init(id: "yucatan"                , name: "Yucatan Peninsula"               , region: "Caribbean"        , latitude:   21.300, longitude:   -90.325, source: .regionalVirtualStations),
    ]

    /// All stations across every supported data source. The ViewModel filters
    /// this down via `stations(for enabled:)`. Stations with the same NOAA
    /// raw ID (e.g. "florida_keys") but different sources are distinct entries
    /// — their composite `id` keeps SwiftUI ForEach and the cache key map clean.
    static var allStations: [VirtualStation] { stations + vsStations }

    /// Stations belonging to one or more enabled sources.
    static func stations(for enabled: Set<DataSource>) -> [VirtualStation] {
        allStations.filter { enabled.contains($0.source) }
    }

    /// Priority subset within the enabled sources. Currently the curated
    /// priority list keys off NOAA raw IDs; many of those names exist in both
    /// the gridded and VS catalogs, so this naturally surfaces a small
    /// marquee set from whichever source the user has enabled.
    static func priorityStations(for enabled: Set<DataSource>) -> [VirtualStation] {
        stations(for: enabled).filter { priorityIDs.contains($0.rawID) }
    }

    /// Everything in the enabled sources that isn't in the priority subset.
    static func extendedStations(for enabled: Set<DataSource>) -> [VirtualStation] {
        stations(for: enabled).filter { !priorityIDs.contains($0.rawID) }
    }
}
